spring:
    application:
        name: securityJWT
    profiles:
        active: dev
        include:
            - base-addi
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
                ddl-auto: update
        show-sql: true

logging:
    level:
        root: info
        com.ll.ebook.app: debug
        org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
        org.springframework.orm.jpa: debug # 콘솔창에 JPA 쿼리 결과 출력